### ISSUE TITLE
CE5: Instructions

### ISSUE THREAD

**Issue by CharlotteRuth** [sagekg/Grinnell-Computational-Physics#13]
I was confused by this sentence: " I've used it to make plotting the grid a little easier down the road, since I'll only have to set up those limits once." Reword?

**Comment by CharlotteRuth** [comment]
Would you mind adding comments about the function of the different libraries you import?

**Comment by CharlotteRuth** [comment]
In second code block, change "###Boundary values here" to give students more direction, e.g. "Set boundary values here"

**Comment by CharlotteRuth** [comment]
Typo: Remember that you can indexing in the meshgrids to find the values for calculating.

**Comment by sagekg** [comment]
I'll also go back through the old exercises and add comments to the first appearance of each package

**Comment by CharlotteRuth** [comment]
In the "Part 3: Sit Back and Relax" section (clever title, btw), be sure to define the variables that appear in the equations.

**Comment by CharlotteRuth** [comment]
Prompt the students to plot before the movie

**Comment by CharlotteRuth** [comment]
Looks like the second instance of “ wframe = ax.plot_wireframe(X, Y, V)” was accidentally left in the student version of the code

**Comment by CharlotteRuth** [comment]
Tell the students to call their iterator counter “total_iter” and not update it within the movie

**Comment by CharlotteRuth** [comment]
It might be good to prompt the students to save their initial guess so that they can refer back to it when running the movie as opposed to regenerating the initial guess.

**Comment by CharlotteRuth** [comment]
I was tripped up because I forgot that I needed to use np.copy to generate V_last rather than just V_last = V. Maybe something to prompt the students about?

**Comment by sagekg** [comment]
> Looks like the second instance of “ wframe = ax.plot_wireframe(X, Y, V)” was accidentally left in the student version of the code

I actually left this in intentionally as a prompt both times, in the hope that would make it a little easier to match variable names with my code for the students

**Comment by CharlotteRuth** [comment]
You mention that students could average over the *8* nearest points. Maybe warn them that they'll have to do a weighted average, if so.

**Comment by CharlotteRuth** [comment]
Clarify that students should generate and look at the animation but that it does not need to be turned in
