### ISSUE TITLE
Clarity of directions

### ISSUE THREAD

**Issue by CharlotteRuth** [sagekg/Grinnell-Computational-Physics#2]
The directions should be made more clear to the students so that they know exactly what they need to turn in. For instance, in "Please write a script which generates a plot of each of these for two point charges," which two charges are being referred to? Restating the two plots would also be helpful. Also, "try plugging in different values for the locations and sizes of the charges. Can you identify any interesting behavior of the field?" should be clarified further. What sort of interesting behavior? What will the students need to turn in to fully answer this question?

**Comment by CharlotteRuth** [comment]
Other things it would be helpful to clarify: do students have to use color, and, if so, what should it represent? What should be the physical range of the plot? Can the vectors be arbitrarily scaled in length so that they are visible?

**Comment by sagekg** [comment]
Ok, I added some clarified some instructions and additional instructions as well as a few hints
