### ISSUE TITLE
CE1: trig bug

### ISSUE THREAD

**Issue by CharlotteRuth** [sagekg/Grinnell-Computational-Physics#8]
I think we need another way around the "factor of 2" problem. Multiplying by a factor of 2 to solve the plot is kind just happenstance that it works. If we weren't plotting a sphere but rather some other shape it wouldn't because there would not be symmetrical values of phi. So prompting students to solve it that way will confuse them and obscure what it actually going on.

Students also might not encounter the error. For instance, I solved the problem like below and never encountered a factor of two difference.

r = np.sqrt(x**2 + y**2 + z**2)
theta = np.arccos(z/r)
phi = np.arctan(y/x)
phi[np.where(y < 0)] = phi[np.where(y < 0)] - np.pi

**Comment by sagekg** [comment]
That's a much better way to handle it, yeah. I've updated my code to to reflect your method, and I changed the hint to include the line <pre><code>phi[np.where(x < 0)] = phi[np.where(x < 0)] - np.pi</code></pre>
I was thinking its best to just give this one to the students, but we could also leave it out and have the hint suggest some info about np.where.
